### ISSUE TITLE
Broken with python 3.6.3

### ISSUE THREAD

**Issue by arthurdarcet** [mwfrojdman/ammoo#5]
the `ammoo/wire/typing.py` file uses the `typing._gveq` internal which has been removed by https://github.com/python/cpython/commit/9e3cd78ec18b2d2078d30b04307916acd68be37a in python 3.6.3

**Comment by mwfrojdman** [comment]
Thanks for the report, I'll check it during the weekend

**Comment by mwfrojdman** [comment]
Python 3.6.1 has `typing.Deque`, which can be used. I'll make a conditional import on Python >= 3.6.1 to fix the issue, and see if we can get rid of the import of that ugly private function too.

**Comment by waza-ari** [comment]
Hi there - anything new on this front? CentOS7 has Python 3.6.3 as only version >3.5 in the repositories, so... we can't use the library at the moment. Unfortunate that such API changes are made in minor versions of Python...

**Comment by rob-blackbourn** [comment]
Hi. I've stumbled on this bug too :( but I used the fork from athurdarcet so I'm up and running :)

This is the best asyncio amqp implementation I've found.

**Comment by arthurdarcet** [comment]
I wouldn't rely too much on my fork… I'm not maintaining it and we've switched to https://github.com/Polyconseil/aioamqp some time ago

**Comment by mwfrojdman** [comment]
Sorry, been busy. I'll just remove the type annotation for that

**Comment by rob-blackbourn** [comment]
Thanks dude!

**Comment by mwfrojdman** [comment]
Fix merged to `master` and `release` branches, I'll do a release to pypi later. Fix version is `1.0.0b2`
